### ISSUE TITLE
Cannot be installed. ImportError: No module named 'field_click_form_edit'

### ISSUE THREAD

**Issue by satriani-vai** [annaduraiVignesh/odoo_field_click_form_edit_v11#1]
```
Fehler:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/local/odoo_11/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/odoo_11/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/local/odoo_11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/local/odoo_11/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/odoo_11/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/odoo_11/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/local/odoo_11/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/odoo_11/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/local/odoo_11/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/local/odoo_11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/local/odoo_11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/usr/local/odoo_11/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/.local/share/Odoo/addons/11.0/auto_invoice_workflow_ept/models/custom_base_sale.py", line 110, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/local/odoo_11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 121, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/local/odoo_11/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/usr/local/odoo_11/odoo/modules/module.py", line 61, in load_module
    f, path, (_suffix, _mode, type_) = imp.find_module(addon_name, ad_paths)
  File "/usr/local/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'field_click_form_edit'
```

**Comment by intoku** [comment]
also same error, on v.11, - is this plugin functional at all?

**Comment by intoku** [comment]
`Server application error {"message":"Odoo Server Error","data":{"message":"No module named 'field_click_form_edit'","arguments":["No module named 'field_click_form_edit'"],"exception_type":"internal_error","debug":"Traceback (most recent call last):\n  File \"/home/ODONEW/ODONEW-server/odoo/http.py\", line 647, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/ODONEW/ODONEW-server/odoo/http.py\", line 307, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/home/ODONEW/ODONEW-server/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/home/ODONEW/ODONEW-server/odoo/http.py\", line 689, in dispatch\n    result = self._call_function(**self.params)\n  File \"/home/ODONEW/ODONEW-server/odoo/http.py\", line 339, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/home/ODONEW/ODONEW-server/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/home/ODONEW/ODONEW-server/odoo/http.py\", line 332, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/home/ODONEW/ODONEW-server/odoo/http.py\", line 933, in __call__\n    return self.method(*args, **kw)\n  File \"/home/ODONEW/ODONEW-server/odoo/http.py\", line 512, in response_wrap\n    response = f(*args, **kw)\n  File \"/home/ODONEW/ODONEW-server/addons/web/controllers/main.py\", line 934, in call_button\n    action = self._call_kw(model, method, args, {})\n  File \"/home/ODONEW/ODONEW-server/addons/web/controllers/main.py\", line 922, in _call_kw\n    return call_kw(request.env[model], method, args, kwargs)\n  File \"/home/ODONEW/ODONEW-server/odoo/api.py\", line 689, in call_kw\n    return call_kw_multi(method, model, args, kwargs)\n  File \"/home/ODONEW/ODONEW-server/odoo/api.py\", line 680, in call_kw_multi\n    result = method(recs, *args, **kwargs)\n  File \"<decorator-gen-42>\", line 2, in button_immediate_install\n  File \"/home/ODONEW/ODONEW-server/odoo/addons/base/module/module.py\", line 71, in check_and_log\n    return method(self, *args, **kwargs)\n  File \"/home/ODONEW/ODONEW-server/odoo/addons/base/module/module.py\", line 448, in button_immediate_install\n    return self._button_immediate_function(type(self).button_install)\n  File \"/home/ODONEW/ODONEW-server/odoo/addons/base/module/module.py\", line 541, in _button_immediate_function\n    modules.registry.Registry.new(self._cr.dbname, update_module=True)\n  File \"/home/ODONEW/ODONEW-server/odoo/modules/registry.py\", line 85, in new\n    odoo.modules.load_modules(registry._db, force_demo, status, update_module)\n  File \"/home/ODONEW/ODONEW-server/odoo/modules/loading.py\", line 343, in load_modules\n    loaded_modules, update_module)\n  File \"/home/ODONEW/ODONEW-server/odoo/modules/loading.py\", line 242, in load_marked_modules\n    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)\n  File \"/home/ODONEW/ODONEW-server/odoo/modules/loading.py\", line 121, in load_module_graph\n    load_openerp_module(package.name)\n  File \"/home/ODONEW/ODONEW-server/odoo/modules/module.py\", line 368, in load_openerp_module\n    __import__('odoo.addons.' + module_name)\n  File \"/home/ODONEW/ODONEW-server/odoo/modules/module.py\", line 61, in load_module\n    f, path, (_suffix, _mode, type_) = imp.find_module(addon_name, ad_paths)\n  File \"/usr/lib/python3.5/imp.py\", line 296, in find_module\n    raise ImportError(_ERR_MSG.format(name), name=name)\nImportError: No module named 'field_click_form_edit'\n","name":"builtins.ImportError"},"code":200}`

**Comment by satriani-vai** [comment]
Here is a fix for this issue https://github.com/annaduraiVignesh/odoo_field_click_form_edit_v11/pull/2

**Comment by intoku** [comment]
Thank you, installs now. Only Admin users can edit fields? also just on detail view off tasks - Should this work on Kanban titles, or listview?
